packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': false
  prisma: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.16'
  - '@expo/config@57.0.8'
  - '@expo/fingerprint@0.20.8'
  - '@expo/inline-modules@0.1.6'
  - '@expo/log-box@57.0.3'
  - '@expo/metro-runtime@57.0.11'
  - expo-asset@57.0.12
  - expo-constants@57.0.12
  - expo-router@57.0.14
  - expo-splash-screen@57.0.7
  - expo@57.0.14
